import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Nav } from '@/components/Nav'
import { Contador } from '@/components/Contador'
import './index.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                {/* <!-- Encabezado con logos --> */}
                <Header />

                <div className="container">
                    <h1>XI JORNADAS TECNOLÓGICAS</h1>
                    <h1>INGENIERÍA EN SISTEMAS COMPUTACIONALES</h1>
                    {/* <!-- Pestañas de navegación --> */}
                    <Nav />
                    {/* <!-- Contador de tiempo y Mensaje de Evento Iniciado --> */}
                    <Contador />

                    {/* Contenido Principal de la Pagina */}
                    {children}
                </div>
                {/* <!-- Contenido existente... --> */}

                {/* <!-- Pie de página --> */}
                <Footer />
            </body>
        </html>
    )
}
